name: Lparstat

on:
  workflow_dispatch:

jobs:
  generate-logs:
    name: uLimits - ${{ matrix.os }} [${{ matrix.runner_owner }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-ppc64le-p10
            runner_owner: "actions-runner-ppc64le-p10"
            runner_files: "/home/runner/runners/2.321.0/_diag/Runner_*"
            worker_files: "/home/runner/runners/2.321.0/_diag/Worker_*"
          - os: ubuntu-24.04-ppc64le
            runner_owner: "actions-runner-ppc64le"
            runner_files: "/opt/runner/_diag/Runner_*"
            worker_files: "/opt/runner/_diag/Worker_*"
          # - os: ubuntu-24.04-ppc64le
          #   runner_owner: "actions-runner-ppc64le"
          #   runner_files: "/opt/runner/_diag/Runner_*"
          #   worker_files: "/opt/runner/_diag/Worker_*"
          # - os: ubuntu-24.04-ppc64le-osu1
          #   runner_owner: "actions-runner-ppc64le"
          #   runner_files: "/opt/runner/_diag/Runner_*"
          #   worker_files: "/opt/runner/_diag/Worker_*"
          # - os: ubuntu-24.04-powervs-selfhosted
          #   runner_owner: "actions-runner-ppc64le"
          #   runner_files: "/opt/runner/_diag/Runner_*"
          #   worker_files: "/opt/runner/_diag/Worker_*"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: check llparstat
        run: |
          lparstat
          
