name: Setup-java

on:
  workflow_dispatch:

jobs:
  generate-logs:
    name: Runner Info - ${{ matrix.os }} [${{ matrix.runner_owner }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
          os: 
            - ubuntu-24.04-ppc64le
          runner_owner: 
            - "ppc64le-hosted"
          version: [11, 17, 21]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'semeru'
          java-version: '${{ matrix.version }}'
          architecture: ppc64le
