name: Setup-java

on:
  workflow_dispatch:

jobs:
  generate-logs:
    name: Runner Info - ${{ matrix.os }} [${{ matrix.runner_owner }}]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04-ppc64le
            runner_owner: "ppc64le-hosted"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'semeru'
          java-version: '${{ matrix.version }}'
          cache: maven
          architecture: ppc64le
